import React, { useState, useEffect } from 'react';
import { ScrollArea } from '../ui/scroll-area';
import { Button } from '../ui/button';
import { Textarea } from '../ui/textarea';
import { Badge } from '../ui/badge';
import { Separator } from '../ui/separator';
import { Mail, Send, RefreshCw, Edit3, Clock, User as UserIcon, Sparkles, CheckCircle2 } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { messageAPI, aiToolsAPI } from '../../lib/api';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';

const ThreadPanel = ({ ticketDetails, onTicketUpdate }) => {
  const { user } = useAuth();
  const [replyBody, setReplyBody] = useState('');
  const [sending, setSending] = useState(false);
  const [generatingDraft, setGeneratingDraft] = useState(false);
  const [aiDraft, setAiDraft] = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Auto-generate AI draft when ticket opens
  useEffect(() => {
    if (ticketDetails && !hasAutoGenerated) {
      handleGenerateDraft(true);
      setHasAutoGenerated(true);
    }
  }, [ticketDetails?.ticket?.id]);

  // Reset when ticket changes
  useEffect(() => {
    setHasAutoGenerated(false);
    setIsEditing(false);
    setAiDraft(null);
    setReplyBody('');
  }, [ticketDetails?.ticket?.id]);

  if (!ticketDetails) {
    return (
      <div className="flex-1 flex items-center justify-center bg-white" data-testid="thread-panel-empty">
        <div className="text-center">
          <Mail className="w-16 h-16 mx-auto mb-4 text-[#CBD5E1]" />
          <p className="text-lg font-medium text-[#605E5C]">Select a ticket to view details</p>
          <p className="text-sm text-[#8A8886] mt-1">Choose from the list on the left</p>
        </div>
      </div>
    );
  }

  const { ticket, messages, student } = ticketDetails;

  const handleSendReply = async () => {
    const bodyToSend = isEditing ? replyBody : aiDraft?.safe_reply;
    
    if (!bodyToSend?.trim()) {
      toast.error('Please enter a message');
      return;
    }

    setSending(true);
    try {
      await messageAPI.create(ticket.id, bodyToSend, 'outbound');
      setReplyBody('');
      setAiDraft(null);
      setIsEditing(false);
      setHasAutoGenerated(false);
      toast.success('Reply sent successfully');
      onTicketUpdate();
    } catch (error) {
      toast.error('Failed to send reply');
    } finally {
      setSending(false);
    }
  };

  const handleGenerateDraft = async (isAuto = false) => {
    const latestInbound = messages?.filter(m => m.direction === 'inbound').pop();
    if (!latestInbound) {
      if (!isAuto) toast.error('No student message to reply to');
      return;
    }

    setGeneratingDraft(true);
    try {
      const draftRequest = {
        institution_id: user.institution_id,
        ticket_id: ticket.id,
        student_email: student.email,
        student_name: student.name,
        latest_message: latestInbound.body,
        thread_context: messages.slice(-3).map(m => ({
          sender: m.sender_email,
          body: m.body,
        })),
        student_notes: student.notes,
      };

      const draft = await aiToolsAPI.draftReply(draftRequest);
      setAiDraft(draft);
      setReplyBody(draft.safe_reply);
      setIsEditing(false);
      if (!isAuto) toast.success('AI draft regenerated');
    } catch (error) {
      if (!isAuto) toast.error('Failed to generate AI draft');
    } finally {
      setGeneratingDraft(false);
    }
  };

  const handleEdit = () => {
    setIsEditing(true);
  };

  return (
    <div className="flex-1 flex flex-col bg-white border-r border-[#EDEBE9]" data-testid="thread-panel">
      {/* Email Header - Outlook Style */}
      <div className="p-4 border-b border-[#EDEBE9] bg-[#FAF9F8]">
        <div className="flex items-start justify-between mb-3">
          <div className="flex-1">
            <h2 className="text-xl font-semibold text-[#323130] mb-1">
              {ticket.subject}
            </h2>
            <div className="flex items-center space-x-3 text-sm text-[#605E5C]">
              <span className="font-medium">{student.name}</span>
              <span className="text-[#8A8886]">&lt;{student.email}&gt;</span>
              <Badge className="text-xs capitalize bg-[#E1DFDD] text-[#323130] hover:bg-[#D2D0CE]">
                {ticket.category.replace('_', ' ')}
              </Badge>
            </div>
          </div>
        </div>
      </div>

      {/* Message Thread */}
      <ScrollArea className="flex-1 p-4 bg-white">
        <div className="space-y-4 max-w-4xl">
          {messages.length === 0 ? (
            <div className="text-center py-8">
              <p className="text-sm text-[#8A8886]">No messages yet</p>
            </div>
          ) : (
            messages.map((message, index) => (
              <div key={message.id} data-testid={`message-${message.id}`}>
                {index > 0 && <Separator className="my-4" />}
                <div className="flex items-start space-x-3">
                  <div className="w-10 h-10 rounded-full bg-[#0078D4] flex items-center justify-center text-white font-semibold">
                    {message.direction === 'inbound'
                      ? student.name.charAt(0).toUpperCase()
                      : user.name.charAt(0).toUpperCase()}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <span className="font-semibold text-[#323130]">
                        {message.direction === 'inbound' ? student.name : user.name}
                      </span>
                      <span className="text-xs text-[#8A8886]">
                        {formatDistanceToNow(new Date(message.created_at), { addSuffix: true })}
                      </span>
                    </div>
                    <div className="text-sm text-[#323130] whitespace-pre-wrap leading-relaxed">
                      {message.body}
                    </div>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </ScrollArea>

      <Separator />

      {/* AI Draft / Reply Section - Outlook Style */}
      <div className="p-4 bg-white">
        {/* AI Draft Status Banner */}
        {generatingDraft ? (
          <div className="mb-4 p-3 bg-[#FFF4CE] border border-[#F3D03E] rounded-md flex items-center space-x-2">
            <Clock className="w-4 h-4 text-[#797775] animate-spin" />
            <span className="text-sm text-[#323130]">Generating AI-powered reply...</span>
          </div>
        ) : aiDraft && !isEditing ? (
          <div className="mb-4 p-3 bg-[#DFF6DD] border border-[#10893E] rounded-md">
            <div className="flex items-start justify-between">
              <div className="flex items-start space-x-2 flex-1">
                <Sparkles className="w-4 h-4 text-[#10893E] mt-0.5" />
                <div className="flex-1">
                  <p className="text-sm font-semibold text-[#323130] mb-1">AI-Suggested Reply Ready</p>
                  <p className="text-xs text-[#605E5C] mb-2">{aiDraft.summary}</p>
                  {aiDraft.cited_kb && aiDraft.cited_kb.length > 0 && (
                    <div className="text-xs text-[#605E5C]">
                      <span className="font-medium">References: </span>
                      {aiDraft.cited_kb.map((kb, i) => kb.title).join(', ')}
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        ) : null}

        {/* Reply Actions - Outlook Style Ribbon */}
        <div className="flex items-center space-x-2 mb-3">
          <Button
            onClick={handleSendReply}
            disabled={sending || generatingDraft || (!aiDraft && !replyBody.trim())}
            className="bg-[#0078D4] hover:bg-[#106EBE] text-white font-semibold px-6"
            data-testid="send-reply-btn"
          >
            {sending ? (
              <Clock className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Send className="w-4 h-4 mr-2" />
            )}
            Send
          </Button>

          {aiDraft && !isEditing && (
            <>
              <Button
                variant="outline"
                onClick={handleEdit}
                disabled={generatingDraft}
                className="border-[#8A8886] text-[#323130] hover:bg-[#F3F2F1]"
                data-testid="edit-draft-btn"
              >
                <Edit3 className="w-4 h-4 mr-2" />
                Edit
              </Button>
              <Button
                variant="outline"
                onClick={() => handleGenerateDraft(false)}
                disabled={generatingDraft}
                className="border-[#8A8886] text-[#323130] hover:bg-[#F3F2F1]"
                data-testid="regenerate-draft-btn"
              >
                <RefreshCw className="w-4 h-4 mr-2" />
                Regenerate
              </Button>
            </>
          )}
        </div>

        {/* Reply Composer */}
        <div>
          <Textarea
            placeholder="Type your reply here..."
            value={isEditing || !aiDraft ? replyBody : aiDraft.safe_reply}
            onChange={(e) => setReplyBody(e.target.value)}
            disabled={!isEditing && aiDraft && !generatingDraft}
            rows={10}
            className="resize-none border-[#8A8886] focus:border-[#0078D4] font-sans text-sm"
            data-testid="reply-textarea"
          />
        </div>

        {/* Disclaimer */}
        {aiDraft && (
          <div className="mt-2 text-xs text-[#8A8886] italic">
            AI-generated content. Please review before sending.
          </div>
        )}
      </div>
    </div>
  );
};

export default ThreadPanel;
