import React, { useState, useEffect } from 'react';
import { ScrollArea } from '../ui/scroll-area';
import { Button } from '../ui/button';
import { Textarea } from '../ui/textarea';
import { Badge } from '../ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Separator } from '../ui/separator';
import { Mail, Send, RefreshCw, Edit3, Sparkles, User, Phone, ExternalLink, Clock, MessageSquare, PhoneCall, UserCheck, ArrowRight } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { messageAPI, aiToolsAPI, studentAPI } from '../../lib/api';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';

const TicketDetails = ({ ticketDetails, onTicketUpdate }) => {
  const { user } = useAuth();
  const [replyBody, setReplyBody] = useState('');
  const [sending, setSending] = useState(false);
  const [generatingDraft, setGeneratingDraft] = useState(false);
  const [aiDraft, setAiDraft] = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [editingNotes, setEditingNotes] = useState(false);
  const [notes, setNotes] = useState('');
  const [timeline, setTimeline] = useState([]);

  // Auto-generate AI draft when ticket opens
  useEffect(() => {
    if (ticketDetails && !hasAutoGenerated) {
      handleGenerateDraft(true);
      setHasAutoGenerated(true);
    }
  }, [ticketDetails?.ticket?.id]);

  useEffect(() => {
    setHasAutoGenerated(false);
    setIsEditing(false);
    setAiDraft(null);
    setReplyBody('');
  }, [ticketDetails?.ticket?.id]);

  useEffect(() => {
    if (ticketDetails?.student) {
      setNotes(ticketDetails.student.notes || '');
      loadTimeline(ticketDetails.student.id);
    }
  }, [ticketDetails]);

  const loadTimeline = async (studentId) => {
    try {
      const data = await studentAPI.get(studentId);
      setTimeline(data.timeline || []);
    } catch (error) {
      console.error('Failed to load timeline:', error);
    }
  };

  const handleSaveNotes = async () => {
    try {
      await studentAPI.update(ticketDetails.student.id, { notes });
      toast.success('Notes saved');
      setEditingNotes(false);
      onTicketUpdate();
    } catch (error) {
      toast.error('Failed to save notes');
    }
  };

  if (!ticketDetails) {
    return (
      <div className="flex-1 flex items-center justify-center bg-gray-50" data-testid="ticket-details-empty">
        <div className="text-center">
          <Mail className="w-16 h-16 mx-auto mb-4 text-gray-200" />
          <p className="text-base font-medium text-gray-900">Select a ticket</p>
          <p className="text-sm text-gray-500 mt-1">Choose a ticket from the list to view details</p>
        </div>
      </div>
    );
  }

  const { ticket, messages, student } = ticketDetails;

  const handleSendReply = async () => {
    const bodyToSend = isEditing ? replyBody : aiDraft?.safe_reply;
    
    if (!bodyToSend?.trim()) {
      toast.error('Please enter a message');
      return;
    }

    setSending(true);
    try {
      await messageAPI.create(ticket.id, bodyToSend, 'outbound');
      setReplyBody('');
      setAiDraft(null);
      setIsEditing(false);
      setHasAutoGenerated(false);
      toast.success('Reply sent');
      onTicketUpdate();
    } catch (error) {
      toast.error('Failed to send reply');
    } finally {
      setSending(false);
    }
  };

  const handleGenerateDraft = async (isAuto = false) => {
    const latestInbound = messages?.filter(m => m.direction === 'inbound').pop();
    if (!latestInbound) {
      if (!isAuto) toast.error('No student message to reply to');
      return;
    }

    setGeneratingDraft(true);
    
    // Create a timeout promise
    const timeout = new Promise((_, reject) => 
      setTimeout(() => reject(new Error('Draft generation timed out')), 30000)
    );
    
    try {
      const draftRequest = {
        institution_id: user.institution_id,
        ticket_id: ticket.id,
        student_email: student.email,
        student_name: student.name,
        latest_message: latestInbound.body,
        thread_context: messages.slice(-3).map(m => ({
          sender: m.sender_email,
          body: m.body,
        })),
        student_notes: student.notes,
      };

      // Race between API call and timeout
      const draft = await Promise.race([
        aiToolsAPI.draftReply(draftRequest),
        timeout
      ]);
      
      setAiDraft(draft);
      setReplyBody(draft.safe_reply);
      setIsEditing(false);
      if (!isAuto) toast.success('AI draft regenerated');
    } catch (error) {
      console.error('Draft generation error:', error);
      if (error.message === 'Draft generation timed out') {
        toast.error('AI draft is taking longer than expected. Please try regenerating.');
      } else {
        if (!isAuto) toast.error('Failed to generate AI draft');
      }
      // Set editing mode so user can still type manually
      setIsEditing(true);
    } finally {
      setGeneratingDraft(false);
    }
  };

  const getEventIcon = (eventType) => {
    const icons = {
      note: <MessageSquare className="w-3.5 h-3.5 text-blue-600" />,
      phone_call: <PhoneCall className="w-3.5 h-3.5 text-purple-600" />,
      walk_in: <UserCheck className="w-3.5 h-3.5 text-orange-600" />,
      ai_routed: <Sparkles className="w-3.5 h-3.5 text-green-600" />,
      sent_email: <Mail className="w-3.5 h-3.5 text-blue-600" />,
      received_email: <Mail className="w-3.5 h-3.5 text-gray-600" />,
    };
    return icons[eventType] || <ArrowRight className="w-3.5 h-3.5 text-gray-400" />;
  };

  return (
    <div className="flex-1 bg-gray-50 overflow-hidden" data-testid="ticket-details">
      <ScrollArea className="h-full">
        <div className="max-w-4xl mx-auto p-6 space-y-6">
          {/* Ticket Header Card */}
          <Card className="border-gray-200 shadow-sm">
            <CardHeader className="pb-4">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <CardTitle className="text-xl font-semibold text-gray-900 mb-2">
                    {ticket.subject}
                  </CardTitle>
                  <div className="flex items-center space-x-3 text-sm text-gray-600">
                    <span className="font-medium">{student.name}</span>
                    <span className="text-gray-400">•</span>
                    <span>{student.email}</span>
                    <Badge className="capitalize bg-gray-100 text-gray-700 border-gray-200">
                      {ticket.category.replace('_', ' ')}
                    </Badge>
                  </div>
                </div>
              </div>
            </CardHeader>
          </Card>

          {/* Two Column Layout */}
          <div className="grid grid-cols-2 gap-6">
            {/* Left Column: Messages */}
            <div className="space-y-6">
              <Card className="border-gray-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="text-base font-semibold text-gray-900">Conversation</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {messages.map((message, index) => (
                    <div key={message.id} className="space-y-3">
                      {index > 0 && <Separator />}
                      <div className="flex items-start space-x-3">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-white text-xs font-medium flex-shrink-0">
                          {message.direction === 'inbound'
                            ? student.name.charAt(0).toUpperCase()
                            : user.name.charAt(0).toUpperCase()}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center space-x-2 mb-1">
                            <span className="text-sm font-medium text-gray-900">
                              {message.direction === 'inbound' ? student.name : user.name}
                            </span>
                            <span className="text-xs text-gray-500">
                              {formatDistanceToNow(new Date(message.created_at), { addSuffix: true })}
                            </span>
                          </div>
                          <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">
                            {message.body}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>

            {/* Right Column: Student Info + Timeline */}
            <div className="space-y-6">
              {/* Student Profile */}
              <Card className="border-gray-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="text-base font-semibold text-gray-900">Student Profile</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-start space-x-3">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-white text-lg font-medium">
                      {student.name.charAt(0).toUpperCase()}
                    </div>
                    <div className="flex-1">
                      <h3 className="font-semibold text-gray-900">{student.name}</h3>
                      <p className="text-sm text-gray-500">ID: {student.student_id || 'N/A'}</p>
                    </div>
                  </div>

                  <div className="space-y-2 text-sm">
                    <div className="flex items-center space-x-2 text-gray-600">
                      <Mail className="w-4 h-4 text-gray-400" />
                      <span>{student.email}</span>
                    </div>
                    {student.phone && (
                      <div className="flex items-center space-x-2 text-gray-600">
                        <Phone className="w-4 h-4 text-gray-400" />
                        <span>{student.phone}</span>
                      </div>
                    )}
                    {student.sis_url && (
                      <a
                        href={student.sis_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center space-x-2 text-blue-600 hover:text-blue-700"
                      >
                        <ExternalLink className="w-4 h-4" />
                        <span>View in SIS</span>
                      </a>
                    )}
                  </div>

                  <Separator />

                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-sm font-medium text-gray-900">Notes</label>
                      {!editingNotes && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => setEditingNotes(true)}
                          className="h-7 text-xs"
                        >
                          <Edit3 className="w-3 h-3 mr-1" />
                          Edit
                        </Button>
                      )}
                    </div>
                    {editingNotes ? (
                      <div className="space-y-2">
                        <Textarea
                          value={notes}
                          onChange={(e) => setNotes(e.target.value)}
                          rows={3}
                          className="text-sm"
                        />
                        <div className="flex space-x-2">
                          <Button size="sm" onClick={handleSaveNotes} className="h-7 text-xs">
                            Save
                          </Button>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => {
                              setNotes(student.notes || '');
                              setEditingNotes(false);
                            }}
                            className="h-7 text-xs"
                          >
                            Cancel
                          </Button>
                        </div>
                      </div>
                    ) : (
                      <p className="text-sm text-gray-600">
                        {student.notes || 'No notes yet'}
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Timeline */}
              <Card className="border-gray-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="text-base font-semibold text-gray-900">Timeline</CardTitle>
                </CardHeader>
                <CardContent>
                  {timeline.length === 0 ? (
                    <p className="text-sm text-gray-500 text-center py-4">No events yet</p>
                  ) : (
                    <div className="space-y-3">
                      {timeline.slice(0, 5).map((event) => (
                        <div key={event.id} className="flex items-start space-x-2">
                          <div className="mt-0.5">{getEventIcon(event.event_type)}</div>
                          <div className="flex-1 min-w-0">
                            <p className="text-xs font-medium text-gray-900 capitalize">
                              {event.event_type.replace('_', ' ')}
                            </p>
                            <p className="text-xs text-gray-600 line-clamp-2">{event.content}</p>
                            <p className="text-xs text-gray-400 mt-0.5">
                              {formatDistanceToNow(new Date(event.created_at), { addSuffix: true })}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>

          {/* AI Draft Reply Section */}
          <Card className="border-gray-200 shadow-sm">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="text-base font-semibold text-gray-900">Reply</CardTitle>
                {aiDraft && !isEditing && (
                  <div className="flex items-center space-x-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setIsEditing(true)}
                      disabled={generatingDraft}
                      className="h-8 text-xs"
                    >
                      <Edit3 className="w-3 h-3 mr-1" />
                      Edit
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleGenerateDraft(false)}
                      disabled={generatingDraft}
                      className="h-8 text-xs"
                    >
                      <RefreshCw className="w-3 h-3 mr-1" />
                      Regenerate
                    </Button>
                  </div>
                )}
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* AI Status Banner */}
              {generatingDraft ? (
                <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg flex items-center space-x-2">
                  <Clock className="w-4 h-4 text-amber-600 animate-spin" />
                  <span className="text-sm text-amber-900">Generating AI-powered reply...</span>
                </div>
              ) : aiDraft && !isEditing ? (
                <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
                  <div className="flex items-start space-x-2">
                    <Sparkles className="w-4 h-4 text-green-600 mt-0.5" />
                    <div className="flex-1">
                      <p className="text-sm font-medium text-green-900 mb-1">AI Draft Ready</p>
                      <p className="text-xs text-green-700">{aiDraft.summary}</p>
                      {aiDraft.cited_kb && aiDraft.cited_kb.length > 0 && (
                        <p className="text-xs text-green-600 mt-1">
                          References: {aiDraft.cited_kb.map(kb => kb.title).join(', ')}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              ) : null}

              <Textarea
                placeholder="Type your reply..."
                value={isEditing || !aiDraft ? replyBody : aiDraft.safe_reply}
                onChange={(e) => setReplyBody(e.target.value)}
                disabled={!isEditing && aiDraft && !generatingDraft}
                rows={8}
                className="resize-none text-sm"
              />

              <div className="flex items-center justify-between">
                <p className="text-xs text-gray-500">
                  {aiDraft && 'AI-generated content. Please review before sending.'}
                </p>
                <Button
                  onClick={handleSendReply}
                  disabled={sending || generatingDraft || (!aiDraft && !replyBody.trim())}
                  className="bg-gray-900 hover:bg-gray-800 text-white"
                >
                  {sending ? (
                    <Clock className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Send className="w-4 h-4 mr-2" />
                  )}
                  Send Reply
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </ScrollArea>
    </div>
  );
};

export default TicketDetails;
